/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}", // Isso garante que ele leia tudo dentro de src
    ],
    theme: {
        extend: {
            colors: {
                "primary-navy": "#0C2C47",
                "teal-custom": "#4A9D95",
                "orange-custom": "#E2A54D",
                "mint-light": "#E4F2EA",
                "mint-accent": "#B8F2E6",
                "inverse-on-surface": "#eff0fa",
                "surface-container-highest": "#e0e2ec",
                "inverse-primary": "#adc7ff",
                "on-surface-variant": "#414754",
                "prsimary-fixed-dim": "#adc7ff",
                "surface-container": "#ecedf7",
                "secondary-container": "#B8F2E6",
                "on-primary-fixed": "#001a41",
                "outline-variant": "#c1c6d6",
                "background": "#f9f9ff",
                "secondary-fixed-dim": "#88d982",
                "tertiary": "#E2A54D",
                "on-primary-container": "#ffffff",
                "on-tertiary-fixed-variant": "#5c4300",
                "surface-container-high": "#e6e8f2",
                "on-tertiary": "#ffffff",
                "inverse-surface": "#2d3038",
                "error": "#ba1a1a",
                "tertiary-container": "#E2A54D",
                "surface": "#f9f9ff",
                "on-tertiary-fixed": "#261a00",
                "surface-bright": "#f9f9ff",
                "on-primary-fixed-variant": "#004493",
                "primary": "#0C2C47",
                "primary-fixed": "#E4F2EA",
                "on-background": "#191c23",
                "on-error": "#ffffff",
                "on-secondary-fixed": "#002204",
                "on-error-container": "#93000a",
                "surface-container-low": "#f2f3fd",
                "on-primary": "#ffffff",
                "on-secondary": "#0C2C47",
                "primary-container": "#0C2C47",
                "outline": "#727785",
                "secondary-fixed": "#B8F2E6",
                "surface-tint": "#0C2C47",
                "error-container": "#ffdad6",
                "surface-variant": "#e0e2ec",
                "on-secondary-container": "#0C2C47",
                "on-secondary-fixed-variant": "#005312",
                "tertiary-fixed": "#E2A54D",
                "tertiary-fixed-dim": "#E2A54D",
                "surface-container-lowest": "#ffffff",
                "secondary": "#4A9D95",
                "surface-dim": "#d8d9e3",
                "on-surface": "#191c23"
            },
            fontFamily: {
                'headline': ['Montserrat', 'sans-serif'],
                'sans': ['Inter', 'sans-serif'],
            },
        },
    },
    plugins: [],
}