#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/vscode/vscode-server/bin/linux-x64/cfbea10c5ffb233ea9177d34726e6056e89913dc/node" "/app/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/copilotCLIShim.js" "$@"