"""fix: revert vector to 768 dimensions

Revision ID: 06f85f42ea50
Revises: a72b64d50b4a
Create Date: 2026-04-19 22:20:17.953232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f85f42ea50'
down_revision: Union[str, None] = 'a72b64d50b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
