"""fix: revert vector to 3072 dimensions for gemini-embedding-001

Revision ID: 5e94a2d25482
Revises: 06f85f42ea50
Create Date: 2026-04-19 22:27:17.647045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e94a2d25482'
down_revision: Union[str, None] = '06f85f42ea50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
