"""Add chat history

Revision ID: 6ea6fedc0a62
Revises: 4d1196d7d9a1
Create Date: 2026-04-14 00:51:56.928615

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ea6fedc0a62'
down_revision: Union[str, Sequence[str], None] = '4d1196d7d9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_student_id'), 'chat_sessions', ['student_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_table('document_embeddings')
    op.drop_table('documents')
    op.drop_index('users_email_key', table_name='users')
    op.drop_table('users')
    op.drop_table('_prisma_migrations')
    op.alter_column('answers', 'content_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('answers_assessment_id_fkey', 'answers', type_='foreignkey')
    op.drop_constraint('answers_student_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'answers', 'assessments', ['assessment_id'], ['id'])
    op.alter_column('assessments', 'title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('assessments', 'subject',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('knowledge_base', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledge_base', 'source',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('knowledge_base', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('schools', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('schools', 'name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('schools', 'address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('schools', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('students', 'full_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('students', 'email',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('students_email_key', table_name='students')
    op.create_unique_constraint(None, 'students', ['email'])
    op.drop_constraint('students_school_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'schools', ['school_id'], ['id'])
    op.alter_column('tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('tokens_token_key', table_name='tokens')
    op.create_index(op.f('ix_tokens_token'), 'tokens', ['token'], unique=True)
    op.drop_constraint('tokens_assessment_id_fkey', 'tokens', type_='foreignkey')
    op.drop_constraint('tokens_student_id_fkey', 'tokens', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tokens_student_id_fkey', 'tokens', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tokens_assessment_id_fkey', 'tokens', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tokens_token'), table_name='tokens')
    op.create_index('tokens_token_key', 'tokens', ['token'], unique=True)
    op.alter_column('tokens', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True, precision=6),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tokens', 'used_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True, precision=6),
               existing_nullable=True)
    op.alter_column('tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True, precision=6),
               existing_nullable=True)
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_school_id_fkey', 'students', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'students', type_='unique')
    op.create_index('students_email_key', 'students', ['email'], unique=True)
    op.alter_column('students', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True, precision=6),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('students', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('students', 'full_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('schools', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True, precision=6),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('schools', 'address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('schools', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('schools', 'updated_at')
    op.alter_column('knowledge_base', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True, precision=6),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base', 'source',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('knowledge_base', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledge_base', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('assessments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True, precision=6),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('assessments', 'subject',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assessments', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_student_id_fkey', 'answers', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('answers_assessment_id_fkey', 'answers', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('answers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True, precision=6),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('answers', 'content_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='_prisma_migrations_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=6), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('users_email_key', 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=6), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='documents_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='documents_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('document_embeddings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=6), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_embeddings_document_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='document_embeddings_pkey')
    )
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_student_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
