"""update vector dim to 3072

Revision ID: a72b64d50b4a
Revises: 5bb7c83e59f8
Create Date: 2026-04-19 22:12:59.450823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72b64d50b4a'
down_revision: Union[str, None] = '5bb7c83e59f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
