"""add_document_and_document_chunk

Revision ID: a8744f4e2894
Revises: e81f2739edf9
Create Date: 2026-05-17 15:34:52.636764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'a8744f4e2894'
down_revision: Union[str, None] = 'e81f2739edf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('conteudo_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_student_link_codes_code', table_name='student_link_codes')
    op.drop_table('student_link_codes')
    op.drop_column('students', 'turma')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('turma', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('student_link_codes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email_responsavel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome_responsavel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_link_codes_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_link_codes_pkey')
    )
    op.create_index('ix_student_link_codes_code', 'student_link_codes', ['code'], unique=True)
    op.drop_table('document_chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
