"""add_turma_and_student_link_code

Revision ID: c394475324ed
Revises: e81f2739edf9
Create Date: 2026-05-17 15:26:29.927468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c394475324ed'
down_revision: Union[str, None] = 'e81f2739edf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_link_codes',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('email_responsavel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_responsavel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_link_codes_code'), 'student_link_codes', ['code'], unique=True)
    op.add_column('students', sa.Column('turma', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'turma')
    op.drop_index(op.f('ix_student_link_codes_code'), table_name='student_link_codes')
    op.drop_table('student_link_codes')
    # ### end Alembic commands ###
