"""add zero-trust n:m relationships

Revision ID: dedfc4cbb853
Revises: d7d53fe2f089
Create Date: 2026-05-17 13:43:31.688270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dedfc4cbb853'
down_revision: Union[str, None] = 'd7d53fe2f089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_student_links',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'student_id')
    )
    op.create_table('school_student_links',
    sa.Column('school_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('school_id', 'student_id')
    )
    op.add_column('chat_sessions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'user', ['user_id'], ['id'])
    op.drop_constraint('students_school_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'school_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('students_school_id_fkey', 'students', 'schools', ['school_id'], ['id'])
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'user_id')
    op.drop_table('school_student_links')
    op.drop_table('parent_student_links')
    # ### end Alembic commands ###
