"""add tcle fields to user

Revision ID: e81f2739edf9
Revises: dedfc4cbb853
Create Date: 2026-05-17 14:02:34.327357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81f2739edf9'
down_revision: Union[str, None] = 'dedfc4cbb853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('accepted_tcle', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('tcle_accepted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tcle_accepted_at')
    op.drop_column('user', 'accepted_tcle')
    # ### end Alembic commands ###
